---
#used
testing: true

ExposureTimeAbs: 500000
Gain: 0
Gamma: 1
TriggerActivation: RisingEdge
TriggerDelayAbs: 0
TriggerMode: On
TriggerSelector: FrameStart
TriggerSource: Freerun #Line1
Width: 5120
Height: 5120
OffsetX: 0
OffsetY: 0
GainAuto: Off
ExposureAuto: Off
...
#unused
TriggerSoftware: [None]
AcquisitionAbort: [None]
AcquisitionFrameCount: 1
AcquisitionFrameRateAbs: 0.444
AcquisitionFrameRateLimit: 1.25014
AcquisitionMode: Continuous
AcquisitionStart: [None]
AcquisitionStop: [None]
ActionDeviceKey: 0
ActionGroupKey: 0
ActionGroupMask: 0
ActionSelector: 0
BandwidthControlMode: StreamBytesPerSecond
BinningHorizontal: 1
BinningVertical: 1
BlackLevel: 0
BlackLevelSelector: All
ChunkModeActive: 0
DSPSubregionBottom: 5120
DSPSubregionLeft: 0
DSPSubregionRight: 5120
DSPSubregionTop: 0
DecimationHorizontal: 1
DecimationVertical: 1
DefectMaskEnable: 1
DeviceFirmwareVersion: 00.01.54.19199 
DeviceID: 02-2680D-07041
DeviceModelName: GT5120
DevicePartNumber: 02-2680D
DeviceScanType: Areascan
DeviceTemperature: 37.75
DeviceTemperatureSelector: Main
DeviceUserID: 
DeviceVendorName: Allied Vision Technologies
EFLensFStopCurrent: 37.75
EFLensFStopDecrease: [None]
EFLensFStopIncrease: [None]
EFLensFStopMax: 37.75
EFLensFStopMin: 37.75
EFLensFStopStepSize: 4630509657494913056
EFLensFocusCurrent: 4630509657494913056
EFLensFocusDecrease: [None]
EFLensFocusIncrease: [None]
EFLensFocusMax: 4630509657494913056
EFLensFocusMin: 4630509657494913056
EFLensFocusStepSize: 4630509657494913056
EFLensFocusSwitch: 
EFLensID: 4630509657494913056
EFLensInitialize: [None]
EFLensLastError: 
EFLensState: EFLensWaiting
EFLensZoomCurrent: 4630509657494913056
EFLensZoomMax: 4630509657494913056
EFLensZoomMin: 4630509657494913056
EventAcquisitionEnd: 40001
EventAcquisitionEndFrameID: 0
EventAcquisitionEndTimestamp: 0
EventAcquisitionRecordTrigger: 40004
EventAcquisitionRecordTriggerFrameID: 0
EventAcquisitionRecordTriggerTimestamp: 0
EventAcquisitionStart: 40000
EventAcquisitionStartFrameID: 0
EventAcquisitionStartTimestamp: 0
EventAction0: 40020
EventAction0FrameID: 0
EventAction0Timestamp: 0
EventAction1: 40021
EventAction1FrameID: 0
EventAction1Timestamp: 0
EventError: 65535
EventErrorFrameID: 0
EventErrorTimestamp: 0
EventExposureEnd: 40003
EventExposureEndFrameID: 0
EventExposureEndTimestamp: 0
EventExposureStart: 40019
EventExposureStartFrameID: 0
EventExposureStartTimestamp: 0
EventFrameTrigger: 40002
EventFrameTriggerFrameID: 0
EventFrameTriggerReady: 40018
EventFrameTriggerReadyFrameID: 0
EventFrameTriggerReadyTimestamp: 0
EventFrameTriggerTimestamp: 0
EventLine1FallingEdge: 40011
EventLine1FallingEdgeFrameID: 0
EventLine1FallingEdgeTimestamp: 0
EventLine1RisingEdge: 40010
EventLine1RisingEdgeFrameID: 0
EventLine1RisingEdgeTimestamp: 0
EventLine2FallingEdge: 40013
EventLine2FallingEdgeFrameID: 0
EventLine2FallingEdgeTimestamp: 0
EventLine2RisingEdge: 40012
EventLine2RisingEdgeFrameID: 0
EventLine2RisingEdgeTimestamp: 0
EventNotification: Off
EventOverflow: 65534
EventOverflowFrameID: 0
EventOverflowTimestamp: 0
EventPtpSyncLocked: 40006
EventPtpSyncLockedFrameID: 0
EventPtpSyncLockedTimestamp: 0
EventPtpSyncLost: 40005
EventPtpSyncLostFrameID: 0
EventPtpSyncLostTimestamp: 0
EventSelector: AcquisitionStart
EventsEnable1: 0
ExposureAutoAdjustTol: 5
ExposureAutoAlg: Mean
ExposureAutoMax: 500000
ExposureAutoMin: 100
ExposureAutoOutliers: 0
ExposureAutoRate: 100
ExposureAutoTarget: 50
ExposureMode: Timed
FirmwareVerBuild: 19199
FirmwareVerMajor: 1
FirmwareVerMinor: 54
FpncEnable: 1
GVCPCmdRetries: 5
GVCPCmdTimeout: 250
GVSPAdjustPacketSize: [None]
GVSPBurstSize: 32
GVSPDriver: Socket
GVSPFilterVersion: N/A
GVSPHostReceiveBuffers: 512
GVSPMaxLookBack: 30
GVSPMaxRequests: 3
GVSPMaxWaitSize: 100
GVSPMissingSize: 256
GVSPPacketSize: 1500
GVSPTiltingSize: 100
GVSPTimeout: 70
GainAutoAdjustTol: 5
GainAutoMax: 22
GainAutoMin: 0
GainAutoOutliers: 0
GainAutoRate: 100
GainAutoTarget: 50
GainSelector: All
GevCurrentDefaultGateway: 0
GevCurrentIPAddress: 3800745
GevCurrentSubnetMask: 65535
GevDeviceMACAddress: 65246807967
GevHeartbeatInterval: 1450
GevHeartbeatTimeout: 3000
GevIPConfigurationMode: DHCP
GevPersistentDefaultGateway: 0
GevPersistentIPAddress: 0
GevPersistentSubnetMask: 0
GevSCPSPacketSize: 1500
GevTimestampControlLatch: [None]
GevTimestampControlReset: [None]
GevTimestampTickFrequency: 1000000000
GevTimestampValue: 0
HeightMax: 5120
ImageSize: 26214400
LUTAddress: 196608
LUTBitDepthIn: 10
LUTBitDepthOut: 10
LUTEnable: 0
LUTIndex: 0
LUTLoadAll: [None]
LUTMode: Luminance
LUTSaveAll: [None]
LUTSelector: LUT1
LUTSizeBytes: 2048
LUTValue: 1023
MaxNonOverlappedExposure: 596369
MulticastEnable: 0
MulticastIPAddress: 823132143
NonImagePayloadSize: 0
PayloadSize: 26214400
PixelFormat: Mono8
PtpAcquisitionGateTime: 0
PtpMode: Off
PtpStatus: Disabled
RecorderPreEventCount: 0
SensorBits: 10
SensorHeight: 5120
SensorType: Mono
SensorWidth: 5120
StatFrameDelivered: 0
StatFrameDropped: 0
StatFrameRate: 0
StatFrameRescued: 0
StatFrameShoved: 0
StatFrameUnderrun: 0
StatLocalRate: 0
StatPacketErrors: 0
StatPacketMissed: 0
StatPacketReceived: 0
StatPacketRequested: 0
StatPacketResent: 0
StatTimeElapsed: 0
StreamAnnounceBufferMinimum: 1
StreamAnnouncedBufferCount: 0
StreamBufferHandlingMode: Default
StreamBytesPerSecond: 115000000
StreamFrameRateConstrain: 1
StreamHoldCapacity: 4
StreamHoldEnable: Off
StreamID: DEV_000F3103479F-Stream-000
StreamType: GEV
StrobeDelay: 0
StrobeDuration: 0
StrobeDurationMode: Source
StrobeSource: FrameTrigger
SyncInGlitchFilter: 0
SyncInLevels: 0
SyncInSelector: SyncIn1
SyncOutLevels: 0
SyncOutPolarity: Normal
SyncOutSelector: SyncOut1
SyncOutSource: Exposing
TriggerOverlap: Off
UserSetDefaultSelector: Default
UserSetLoad: [None]
UserSetSave: [None]
UserSetSelector: Default
WidthMax: 5120

